import sanitizeHtml from 'sanitize-html'

const sanitizeConf = {
  allowedTags: [
    'b',
    'br',
    'i',
    'em',
    's',
    'strong',
    'a',
    'p',
    'u',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'div',
    'font',
    'strike',
    'sub',
    'sup',
    'span',
    'blockquote',
    'ol',
    'li',
    'ul',
    'img',
    'figure',
    'audio',
    'video',
    'source',
    'audio-message',
    'video-message',
  ],
  // selfClosing: ['br'],
  allowedAttributes: {
    a: [
      'href',
      'rel',
      'target',
      'data-aq-link-variant',
      'data-aq-button-style',
    ],
    div: ['style', 'class'],
    font: ['size'],
    span: ['style', 'class'],
    p: ['style', 'class'],
    h1: ['style', 'class'],
    h2: ['style', 'class'],
    h3: ['style', 'class'],
    h4: ['style', 'class'],
    h5: ['style', 'class'],
    h6: ['style', 'class'],
    li: ['style'],
    img: ['src', 'alt', 'title', 'width', 'height', 'loading'],
    figure: ['class', 'style', 'data-src'],
    audio: ['src', 'controls', 'preload'],
    video: ['src', 'controls', 'preload', 'playsinline', 'poster'],
    source: ['src', 'type'],
    'audio-message': ['src', 'title', 'mime', 'class'],
    'video-message': ['src', 'title', 'mime', 'class'],
  },
  allowedStyles: {
    '*': {
      color: [
        /^#([0-9a-f]{3}|[0-9a-f]{6})$/i,
        /^rgb\(\s*(\d{1,3}\s*,\s*){2}\d{1,3}\s*\)$/i,
        /^rgba\(\s*(\d{1,3}\s*,\s*){3}(0|1|0?\.\d+)\s*\)$/i,
      ],
      'font-family': [/^[a-z0-9\s'",-]+$/i],
      'font-size': [/^\d+(px|rem|em|%)$/],
      'text-align': [/^(left|right|center|justify)$/],
    },
  },
}

const sanitize = (html) =>
  sanitizeHtml(html, sanitizeConf).replaceAll('<br />', '<br>')

export default sanitize
